# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testJenkins' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  # Pods for testJenkins

  target 'testJenkinsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testJenkinsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
